default: true

MD024: false  # no-duplicate-heading
MD013:
  line_length: 80      # Limit lines to 80 characters (still allows long lines if you disable this)
  ignore_code_blocks: true
  tables: false
MD033: false           # Allow inline HTML
MD003:
  style: atx           # Use # for headings
MD022: true            # Require blank line before each heading
MD012: true            # Require blank lines around list items
MD047: true            # Require a trailing newline at end of file